name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  
  deploy:
    
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Say Hi
        run: echo "Hello World"
