name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:

  deploy:

    name: Deploy To Production Instance
    runs-on: ubuntu-latest

    steps:

      - name: Pull On Host Machine
        run: echo "Hello World"
